# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               guiocm.github.io
tagline:             ''
description:         ''
url:                 https://guiocm.github.io
baseurl:             'https://guiocm.github.io'
paginate:            5

# About/contact
author:
  name:              Guilherme Marques
  email:             guiocm@gmail.com

# Custom vars
version:             1.0.0
