# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Hic Rhodus hic saltus
tagline:          ''
description:      ''
url:              https://guiocm.github.io
baseurl:          /

author:
  name:           'Guilherme Marques'
  email:          'guiocm@gmail.com'

paginate:         5

# Custom vars
